version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      CLUSTER_NAME: test-cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop
    command: ["sh", "-c", "hdfs namenode -format && /etc/bootstrap.sh -d"]

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      DATA_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
    volumes:
      - datanode1:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      DATA_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
    volumes:
      - datanode2:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      DATA_CONF_dfs_datanode_data_dir: file:///hadoop/dfs/data
    volumes:
      - datanode3:/hadoop/dfs/data
    networks:
      - hadoop
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
    ports:
      - 8088:8088
    volumes:
      - ./data:/mnt/hadoop
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    command: ["sh", "-c", "cp /mnt/hadoop/hadoop-mapreduce-examples-3.2.1.jar /opt/hadoop/share/hadoop/mapreduce/"]

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    networks:
      - hadoop
    depends_on:
      - resourcemanager

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    volumes:
      - historyserver:/hadoop/mapred
    networks:
      - hadoop
    depends_on:
      - namenode
      - resourcemanager
    command: ["sh", "-c", "/etc/bootstrap.sh -d && hdfs dfs -mkdir -p /user/Alumno_AI && hdfs dfs -put /mnt/hadoop/archivo.txt /user/Alumno_AI/"]

volumes:
  namenode:
  datanode1:
  datanode2:
  datanode3:
  historyserver:

networks:
  hadoop:
