services:
  # Hadoop Namenode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - '9870:9870'  # Interfaz web del NameNode
      - '9000:9000'  # Conexiones HDFS
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: test
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      YARN_NODEMANAGER_USER: root
      YARN_RESOURCEMANAGER_USER: root
    networks:
      - shared_network

  # Hadoop DataNode 1
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE_PRECONDITION: "namenode:9000"
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      YARN_NODEMANAGER_USER: root
      YARN_RESOURCEMANAGER_USER: root
    networks:
      - shared_network
    depends_on:
      - namenode

  # Hadoop DataNode 2
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE_PRECONDITION: "namenode:9000"
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      YARN_NODEMANAGER_USER: root
      YARN_RESOURCEMANAGER_USER: root
    networks:
      - shared_network
    depends_on:
      - namenode

  # ResourceManager
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864"
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      YARN_NODEMANAGER_USER: root
      YARN_RESOURCEMANAGER_USER: root
    networks:
      - shared_network
    depends_on:
      - namenode
      - datanode1
      - datanode2

  # HistoryServer
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 resourcemanager:8088"
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      YARN_NODEMANAGER_USER: root
      YARN_RESOURCEMANAGER_USER: root
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      - shared_network
    depends_on:
      - namenode
      - resourcemanager

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:

networks:
  shared_network:
    external: true
